services:
  db:
    image: mongo:7
    container_name: realestate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./REServer/data:/csv:ro

volumes:
  mongodata:
