CREATE TABLE IF NOT EXISTS properties (
    id              SERIAL PRIMARY KEY,
    property_id     BIGINT,
    download_date   DATE,
    council_name    VARCHAR(255),
    purchase_price  BIGINT,
    address         VARCHAR(500),
    post_code       VARCHAR(20),
    property_type   VARCHAR(100),
    strata_lot_number VARCHAR(100),
    property_name   VARCHAR(255),
    area            DOUBLE PRECISION,
    area_type       VARCHAR(100),
    contract_date   DATE,
    settlement_date DATE,
    zoning          VARCHAR(100),
    nature_of_property VARCHAR(100),
    primary_purpose VARCHAR(100),
    legal_description TEXT
);
